spring.application.name=crm-schedule
server.port=9001
logging.config=classpath:crm-logback.xml
logging.file.path=/home/adminuser/crm-schedule/logs
excel.template.path=/home/adminuser/crm-schedule/template.xlsx
excel.file.path=/home/adminuser/savedata
# contract detail export config
excel.detail.template.path=/home/adminuser/crm-schedule/template.xlsx
excel.detail.file.path=/home/adminuser/savedata
# task schedule cron
crm-task.cron=0 0/10 * * * ?
